# argo-helm-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/abhishekpanda0620/gitops-test
    path: helm-argocd/nginx-chart
    targetRevision: HEAD
    helm:
      releaseName: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
