apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-index-html
data:
  index.html: |
    <html>
      <head><title>{{ .Values.pageTitle }}</title></head>
      <body>
        <h1>{{ .Values.pageMessage }}</h1>
      </body>
    </html>
