# argo-rollout-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-rollout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abhishekpanda0620/gitops-test
    targetRevision: HEAD
    path: rollouts-argocd/nginx-rollout
    helm:
      releaseName: nginx-rollout
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
