apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx-bluegreen
  template:
    metadata:
      labels:
        app: nginx-bluegreen
    spec:
      containers:
        - name: nginx
          image: nginx:1.24.0
          ports:
            - containerPort: 80
  strategy:
    blueGreen:
      activeService: nginx-blue
      previewService: nginx-green
      autoPromotionEnabled: true
